stages:
- test
- build
- deploy


variables:
  JEKYLL_ENV: production


test_static_pages:
  image: ruby:2.3
  stage: test
  script:
  - export http_proxy=http://10.0.1.8:8000
  - bundle install
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

build_static_pages:
  image: ruby:2.3
  stage: build
  script:
  - export http_proxy=http://10.0.1.8:8000
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
 
deploy_to_staging:
  image: ubuntu
  stage: deploy
  environment:
    name: staging
    url: https://internal.boc-group.eu/$StagingEnvironmentContext/
  script:
    - echo "Acquire::http::Proxy \"http://10.0.1.8:8000\";" >> /etc/apt/apt.conf
    - apt-get update -qq && apt-get install -y -qq apt-utils sshpass openssh-client
    - cd public/
    - sshpass -p $SSH_Pass scp -r -o StrictHostKeyChecking=no * $SSH_User@$SSH_Host:/var/www/html/$StagingEnvironmentContext
